# Generated by Django 4.2 on 2023-05-04 09:23

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_question_image_alter_quiz_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default='default/no_image.jpg', max_length=255, upload_to=api.models.Quiz.image_upload_to),
        ),
    ]
